"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _env_bool(nom, defaut):
    return os.environ.get(nom, str(defaut)).lower() in ("1", "true", "yes", "oui")


# ── Réglages pilotés par l'environnement ──────────────────────────
# En local (aucune variable définie) : valeurs de développement.
# En production (Render) : définies via le tableau de bord de l'hébergeur.

# Clé secrète : valeur locale par défaut, à remplacer en production par
# la variable d'environnement DJANGO_SECRET_KEY.
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-4d=)-j)0046qf3c@+hg#+t^&khld6t4ugyzwo3t5sdyoa#jc+!",
)

# DEBUG activé en local, désactivé en production (DJANGO_DEBUG=false).
DEBUG = _env_bool("DJANGO_DEBUG", True)

# Hôtes autorisés : localhost en dev + le domaine fourni par Render en prod.
ALLOWED_HOSTS = ["localhost", "127.0.0.1"]
_hote_render = os.environ.get("RENDER_EXTERNAL_HOSTNAME")
if _hote_render:
    ALLOWED_HOSTS.append(_hote_render)
_hotes_sup = os.environ.get("DJANGO_ALLOWED_HOSTS", "")
ALLOWED_HOSTS += [h.strip() for h in _hotes_sup.split(",") if h.strip()]

# Origines de confiance pour le CSRF (formulaires) en HTTPS
CSRF_TRUSTED_ORIGINS = []
if _hote_render:
    CSRF_TRUSTED_ORIGINS.append(f"https://{_hote_render}")
for _o in os.environ.get("DJANGO_CSRF_TRUSTED_ORIGINS", "").split(","):
    if _o.strip():
        CSRF_TRUSTED_ORIGINS.append(_o.strip())


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "suivi",
    "vitrine",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # sert les fichiers statiques en prod
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",  # bilinguisme FR/EN
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],  # surcharges globales (ex. admin)
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.i18n",  # LANGUAGE_CODE dans les templates
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# En production, Render fournit DATABASE_URL (PostgreSQL) ; en local, SQLite.
if os.environ.get("DATABASE_URL"):
    import dj_database_url

    DATABASES = {
        "default": dj_database_url.config(
            conn_max_age=600, ssl_require=True
        )
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "fr"  # langue par défaut

# Langues disponibles dans l'application
LANGUAGES = [
    ("fr", "Français"),
    ("en", "English"),
]

# Dossier des fichiers de traduction (.po / .mo)
LOCALE_PATHS = [BASE_DIR / "locale"]

TIME_ZONE = "Africa/Kinshasa"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"  # collecte pour la production

# WhiteNoise : compression + cache des fichiers statiques en production
STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Fichiers téléversés (sources de vérification)
MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

# ── Sécurité renforcée en production (DEBUG = False) ──────────────
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 2592000  # 30 jours
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_CONTENT_TYPE_NOSNIFF = True

# Connexion par identifiant OU adresse e-mail
AUTHENTICATION_BACKENDS = [
    "vitrine.backends.IdentifiantOuEmailBackend",
]

# Redirections de connexion
# Un visiteur non connecté qui tente d'ouvrir l'application est envoyé
# vers la page « Se connecter ou demander un compte ».
LOGIN_URL = "/acces/"
LOGIN_REDIRECT_URL = "/app/"
LOGOUT_REDIRECT_URL = "/"

# E-mails : console en développement. En production, définir un serveur SMTP
# via les variables EMAIL_HOST / EMAIL_HOST_USER / EMAIL_HOST_PASSWORD.
if os.environ.get("EMAIL_HOST"):
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_HOST = os.environ["EMAIL_HOST"]
    EMAIL_PORT = int(os.environ.get("EMAIL_PORT", 587))
    EMAIL_USE_TLS = _env_bool("EMAIL_USE_TLS", True)
    EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
    EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
else:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
DEFAULT_FROM_EMAIL = os.environ.get(
    "DJANGO_DEFAULT_FROM_EMAIL", "Lumière du Soleil <no-reply@lumieredusoleil.org>"
)

# Administrateurs qui reçoivent les notifications (demandes de compte…)
_admin_email = os.environ.get("DJANGO_ADMIN_EMAIL", "manamboba.balaka@gmail.com")
ADMINS = [("Administrateur", _admin_email)]
