# Generated by Django 6.0.6 on 2026-07-04 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Coordinateur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=150, verbose_name="nom complet")),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="adresse e-mail"
                    ),
                ),
                (
                    "telephone",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="téléphone"
                    ),
                ),
                ("actif", models.BooleanField(default=True, verbose_name="actif")),
            ],
            options={
                "verbose_name": "coordinateur",
                "verbose_name_plural": "coordinateurs",
                "ordering": ["nom"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SuiviEvaluateur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=150, verbose_name="nom complet")),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="adresse e-mail"
                    ),
                ),
                (
                    "telephone",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="téléphone"
                    ),
                ),
                ("actif", models.BooleanField(default=True, verbose_name="actif")),
            ],
            options={
                "verbose_name": "suivi-évaluateur",
                "verbose_name_plural": "suivi-évaluateurs",
                "ordering": ["nom"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DirecteurProjet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=150, verbose_name="nom complet")),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="adresse e-mail"
                    ),
                ),
                (
                    "telephone",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="téléphone"
                    ),
                ),
                ("actif", models.BooleanField(default=True, verbose_name="actif")),
                (
                    "coordinateur",
                    models.ForeignKey(
                        blank=True,
                        help_text="Coordinateur dont dépend ce directeur de projet.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="directeurs",
                        to="suivi.coordinateur",
                        verbose_name="coordinateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "directeur de projet",
                "verbose_name_plural": "directeurs de projet",
                "ordering": ["nom"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Projet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Code court et unique du projet (ex. : AGR-01).",
                        max_length=20,
                        unique=True,
                        verbose_name="code",
                    ),
                ),
                ("nom", models.CharField(max_length=200, verbose_name="nom du projet")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "domaine",
                    models.CharField(
                        blank=True,
                        help_text="Ex. : agriculture, éducation, santé…",
                        max_length=100,
                        verbose_name="domaine d'intervention",
                    ),
                ),
                (
                    "date_debut",
                    models.DateField(
                        blank=True, null=True, verbose_name="date de début"
                    ),
                ),
                (
                    "date_fin",
                    models.DateField(blank=True, null=True, verbose_name="date de fin"),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("preparation", "En préparation"),
                            ("en_cours", "En cours"),
                            ("cloture", "Clôturé"),
                        ],
                        default="en_cours",
                        max_length=20,
                        verbose_name="statut",
                    ),
                ),
                (
                    "directeur",
                    models.ForeignKey(
                        blank=True,
                        help_text="Directeur responsable de ce projet.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projets",
                        to="suivi.directeurprojet",
                        verbose_name="directeur de projet",
                    ),
                ),
                (
                    "suivi_evaluateurs",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Un projet peut être suivi par plusieurs suivi-évaluateurs.",
                        related_name="projets",
                        to="suivi.suivievaluateur",
                        verbose_name="suivi-évaluateurs",
                    ),
                ),
            ],
            options={
                "verbose_name": "projet",
                "verbose_name_plural": "projets",
                "ordering": ["code"],
            },
        ),
    ]
