# Generated by Django 6.0.6 on 2026-07-04 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("suivi", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Indicateur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="Référence courte de l'indicateur (ex. : IND-01).",
                        max_length=30,
                        verbose_name="code",
                    ),
                ),
                ("intitule", models.CharField(max_length=250, verbose_name="intitulé")),
                ("definition", models.TextField(blank=True, verbose_name="définition")),
                (
                    "unite",
                    models.CharField(
                        help_text="Ex. : personnes, hectares, tonnes, %…",
                        max_length=50,
                        verbose_name="unité",
                    ),
                ),
                (
                    "niveau",
                    models.CharField(
                        choices=[
                            ("impact", "Impact"),
                            ("effet", "Effet"),
                            ("produit", "Produit"),
                        ],
                        default="produit",
                        max_length=10,
                        verbose_name="niveau",
                    ),
                ),
                (
                    "mode_calcul",
                    models.TextField(blank=True, verbose_name="mode de calcul"),
                ),
                (
                    "methode_collecte",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="méthode de collecte"
                    ),
                ),
                (
                    "source_donnees",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="source des données"
                    ),
                ),
                (
                    "frequence",
                    models.CharField(
                        choices=[
                            ("mensuelle", "Mensuelle"),
                            ("trimestrielle", "Trimestrielle"),
                            ("semestrielle", "Semestrielle"),
                            ("annuelle", "Annuelle"),
                        ],
                        default="trimestrielle",
                        max_length=15,
                        verbose_name="fréquence de collecte",
                    ),
                ),
                (
                    "baseline",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="valeur de référence (baseline)",
                    ),
                ),
                (
                    "cible_finale",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="cible finale",
                    ),
                ),
                (
                    "seuil_vert",
                    models.PositiveSmallIntegerField(
                        default=90,
                        help_text="Taux à partir duquel l'indicateur est « Atteint ».",
                        verbose_name="seuil vert (%)",
                    ),
                ),
                (
                    "seuil_orange",
                    models.PositiveSmallIntegerField(
                        default=70,
                        help_text="Taux à partir duquel l'indicateur est « À surveiller ».",
                        verbose_name="seuil orange (%)",
                    ),
                ),
                ("actif", models.BooleanField(default=True, verbose_name="actif")),
                (
                    "projet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="indicateurs",
                        to="suivi.projet",
                        verbose_name="projet",
                    ),
                ),
            ],
            options={
                "verbose_name": "indicateur",
                "verbose_name_plural": "indicateurs",
                "ordering": ["projet", "code", "intitule"],
            },
        ),
        migrations.CreateModel(
            name="Realisation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("annee", models.PositiveSmallIntegerField(verbose_name="année")),
                (
                    "periode",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Selon la fréquence de l'indicateur : mois (1-12), trimestre (1-4), semestre (1-2) ou 1 si annuelle.",
                        verbose_name="numéro de période",
                    ),
                ),
                (
                    "valeur",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="valeur réalisée"
                    ),
                ),
                (
                    "commentaire",
                    models.TextField(blank=True, verbose_name="commentaire"),
                ),
                (
                    "date_saisie",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date de saisie"
                    ),
                ),
                (
                    "indicateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="suivi.indicateur",
                        verbose_name="indicateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "réalisation",
                "verbose_name_plural": "réalisations",
                "ordering": ["annee", "periode"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SourceVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200, verbose_name="titre")),
                (
                    "fichier",
                    models.FileField(upload_to="sources/%Y/", verbose_name="fichier"),
                ),
                (
                    "date_ajout",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date d'ajout"
                    ),
                ),
                (
                    "realisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sources",
                        to="suivi.realisation",
                        verbose_name="réalisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "source de vérification",
                "verbose_name_plural": "sources de vérification",
                "ordering": ["-date_ajout"],
            },
        ),
        migrations.CreateModel(
            name="Cible",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("annee", models.PositiveSmallIntegerField(verbose_name="année")),
                (
                    "periode",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Selon la fréquence de l'indicateur : mois (1-12), trimestre (1-4), semestre (1-2) ou 1 si annuelle.",
                        verbose_name="numéro de période",
                    ),
                ),
                (
                    "valeur",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="valeur cible"
                    ),
                ),
                (
                    "indicateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="suivi.indicateur",
                        verbose_name="indicateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "cible",
                "verbose_name_plural": "cibles",
                "ordering": ["annee", "periode"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("indicateur", "annee", "periode"),
                        name="cible_unique_par_periode",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="realisation",
            constraint=models.UniqueConstraint(
                fields=("indicateur", "annee", "periode"),
                name="realisation_unique_par_periode",
            ),
        ),
    ]
