# Generated by Django 6.0.6 on 2026-07-04 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("suivi", "0002_indicateur_realisation_sourceverification_cible_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AxeDesagregation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="nom de l'axe"
                    ),
                ),
                (
                    "modalites",
                    models.CharField(
                        help_text="Valeurs possibles, séparées par des virgules (ex. : Homme, Femme).",
                        max_length=250,
                        verbose_name="modalités",
                    ),
                ),
            ],
            options={
                "verbose_name": "axe de désagrégation",
                "verbose_name_plural": "axes de désagrégation",
                "ordering": ["nom"],
            },
        ),
        migrations.AddField(
            model_name="indicateur",
            name="denominateur_libelle",
            field=models.CharField(
                blank=True,
                help_text="Ex. : nombre total de producteurs ciblés.",
                max_length=200,
                verbose_name="libellé du dénominateur",
            ),
        ),
        migrations.AddField(
            model_name="indicateur",
            name="moyen_verification",
            field=models.CharField(
                blank=True,
                help_text="Ex. : rapports de formation, listes de présence…",
                max_length=250,
                verbose_name="moyen de vérification",
            ),
        ),
        migrations.AddField(
            model_name="indicateur",
            name="numerateur_libelle",
            field=models.CharField(
                blank=True,
                help_text="Ex. : nombre de producteurs formés.",
                max_length=200,
                verbose_name="libellé du numérateur",
            ),
        ),
        migrations.AddField(
            model_name="indicateur",
            name="type_valeur",
            field=models.CharField(
                choices=[
                    ("nombre", "Nombre (valeur saisie directement)"),
                    ("pourcentage", "Pourcentage (numérateur ÷ dénominateur × 100)"),
                    ("ratio", "Ratio (numérateur ÷ dénominateur)"),
                ],
                default="nombre",
                help_text="Pourcentage ou ratio : la valeur se calcule automatiquement à partir du numérateur et du dénominateur saisis à chaque période.",
                max_length=15,
                verbose_name="mode de calcul de la valeur",
            ),
        ),
        migrations.AddField(
            model_name="realisation",
            name="denominateur",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=14,
                null=True,
                verbose_name="dénominateur",
            ),
        ),
        migrations.AddField(
            model_name="realisation",
            name="numerateur",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=14,
                null=True,
                verbose_name="numérateur",
            ),
        ),
        migrations.AlterField(
            model_name="indicateur",
            name="mode_calcul",
            field=models.TextField(
                blank=True, verbose_name="formule / mode de calcul (description)"
            ),
        ),
        migrations.AlterField(
            model_name="indicateur",
            name="niveau",
            field=models.CharField(
                choices=[
                    ("intrant", "Intrant"),
                    ("processus", "Processus"),
                    ("produit", "Produit / Extrant"),
                    ("effet", "Résultat / Effet"),
                    ("impact", "Impact"),
                ],
                default="produit",
                max_length=10,
                verbose_name="type d'indicateur",
            ),
        ),
        migrations.AlterField(
            model_name="realisation",
            name="valeur",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Laisser vide si numérateur et dénominateur sont saisis (calcul automatique).",
                max_digits=14,
                null=True,
                verbose_name="valeur réalisée",
            ),
        ),
        migrations.AddField(
            model_name="indicateur",
            name="desagregations",
            field=models.ManyToManyField(
                blank=True,
                help_text="Ventilations attendues pour cet indicateur (sexe, âge, zone…).",
                related_name="indicateurs",
                to="suivi.axedesagregation",
                verbose_name="axes de désagrégation",
            ),
        ),
        migrations.CreateModel(
            name="VentilationRealisation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modalite",
                    models.CharField(
                        help_text="Ex. : Homme, Femme, 15-24 ans, Zone Nord…",
                        max_length=100,
                        verbose_name="modalité",
                    ),
                ),
                (
                    "valeur",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="valeur"
                    ),
                ),
                (
                    "axe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="suivi.axedesagregation",
                        verbose_name="axe de désagrégation",
                    ),
                ),
                (
                    "realisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ventilations",
                        to="suivi.realisation",
                        verbose_name="réalisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "ventilation",
                "verbose_name_plural": "ventilations",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("realisation", "axe", "modalite"),
                        name="ventilation_unique_par_modalite",
                    )
                ],
            },
        ),
    ]
