# Generated by Django 6.0.6 on 2026-07-19 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("suivi", "0003_axedesagregation_indicateur_denominateur_libelle_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="coordinateur",
            name="utilisateur",
            field=models.OneToOneField(
                blank=True,
                help_text="Compte utilisé par cette personne pour se connecter à l'application.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fiche_%(class)s",
                to=settings.AUTH_USER_MODEL,
                verbose_name="compte de connexion",
            ),
        ),
        migrations.AddField(
            model_name="directeurprojet",
            name="utilisateur",
            field=models.OneToOneField(
                blank=True,
                help_text="Compte utilisé par cette personne pour se connecter à l'application.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fiche_%(class)s",
                to=settings.AUTH_USER_MODEL,
                verbose_name="compte de connexion",
            ),
        ),
        migrations.AddField(
            model_name="suivievaluateur",
            name="utilisateur",
            field=models.OneToOneField(
                blank=True,
                help_text="Compte utilisé par cette personne pour se connecter à l'application.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fiche_%(class)s",
                to=settings.AUTH_USER_MODEL,
                verbose_name="compte de connexion",
            ),
        ),
    ]
