# Generated by Django 6.0.6 on 2026-07-19 17:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("suivi", "0004_coordinateur_utilisateur_directeurprojet_utilisateur_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="indicateur",
            name="date_creation",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="date de création"
            ),
        ),
        migrations.AddField(
            model_name="indicateur",
            name="mode_creation",
            field=models.CharField(
                choices=[("manuel", "Saisie manuelle"), ("import", "Import groupé")],
                default="manuel",
                max_length=10,
                verbose_name="mode de création",
            ),
        ),
        migrations.AddConstraint(
            model_name="indicateur",
            constraint=models.UniqueConstraint(
                condition=models.Q(("code", ""), _negated=True),
                fields=("projet", "code"),
                name="indicateur_code_unique_par_projet",
            ),
        ),
    ]
