# Generated by Django 6.0.6 on 2026-07-11 17:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DemandeCompte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=150, verbose_name="nom complet")),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="adresse e-mail"
                    ),
                ),
                (
                    "organisation",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="organisation"
                    ),
                ),
                (
                    "fonction",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="fonction"
                    ),
                ),
                (
                    "motif",
                    models.TextField(
                        help_text="Pourquoi souhaitez-vous accéder à l'application ?",
                        verbose_name="motif de la demande",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("approuvee", "Approuvée"),
                            ("refusee", "Refusée"),
                        ],
                        default="en_attente",
                        max_length=15,
                        verbose_name="statut",
                    ),
                ),
                (
                    "date_demande",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date de la demande"
                    ),
                ),
                (
                    "date_traitement",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="date de traitement"
                    ),
                ),
            ],
            options={
                "verbose_name": "demande de compte",
                "verbose_name_plural": "demandes de compte",
                "ordering": ["-date_demande"],
            },
        ),
        migrations.CreateModel(
            name="MessageContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=150, verbose_name="nom")),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="adresse e-mail"),
                ),
                ("sujet", models.CharField(max_length=200, verbose_name="sujet")),
                ("message", models.TextField(verbose_name="message")),
                (
                    "date_envoi",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date d'envoi"
                    ),
                ),
                ("traite", models.BooleanField(default=False, verbose_name="traité")),
            ],
            options={
                "verbose_name": "message de contact",
                "verbose_name_plural": "messages de contact",
                "ordering": ["-date_envoi"],
            },
        ),
    ]
